config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users#index"

  resources :users, param: :permalink, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      resources :debit_cards, only: [:index, :show, :new, :create, :edit, :update] do
        post :make_payment, on: :member
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debit_card.rb
class DebitCard < ApplicationRecord
  include ActiveModel::Validations

  before_validation :find_last_four

  validates_presence_of :card_number, :expiration_month, :expiration_year, :cvv, :user_id
  validates_with ExpirationMonthValidator, DuplicateCardValidator

  belongs_to :user

  attr_encrypted :card_number, key: 'a' * 32

  def stub_perform_payment(amount)
    card_number == '4242424242424242' ? '100' : '203'
  end

  private

    def find_last_four
      self.last_four = self.card_number.last(4) if self.card_number.present?
    end

end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations

  validates_presence_of :first_name, :last_name
  validates_with ExistingUserValidator

  before_validation(on: :create) do
    self.permalink ||= build_permalink
  end

  before_validation(on: :update) do
    self.permalink = build_permalink
  end

  has_many :debit_cards

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  private

    def build_permalink
      full_name.parameterize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/debit_cards_controller.rb
class DebitCardsController < ApplicationController
  around_action :handle_errors
  before_action :find_user, only: [:create, :index, :show, :edit, :update, :make_payment]
  before_action :find_debit_card, only: [:show, :edit, :update, :make_payment]

  # class UserNotFound < StandardError; end

  # GET /users/:permalink/debit_cards
  def index
    @debit_cards = DebitCard.where(user_id: @user.id)
  end

  # GET /users/:permalink/debit_cards/:id
  def show
  end

  # GET /users/:permalink/debit_cards/:id/edit
  def edit
  end

  # PUT /users/:permalink/debit_cards/:id
  def update
    update_params = update_params_permit!
    @debit_card.update!(update_params)
    flash[:success] = "Debit card updated successfully!"
    redirect_to debit_card_path(@user.permalink, @debit_card.id)
  end

  def make_payment
    monthly_subscription_amount = 1000 # Note: amount is in cents (1000 => $10.00)
    response_code = @debit_card.stub_perform_payment(monthly_subscription_amount)
    if response_code == '100'
      flash[:success] = "Your payment has been accepted."
    else
      flash[:error] = "Your payment has been declined. Please re-check with the providing bank."
    end
    redirect_to debit_card_path(@user.permalink, @debit_card.id)
  end

  # GET /users/:permalink/debit_cards/new
  def new
    new_params = new_params_permit!
    @user = User.find_by_permalink!(new_params[:permalink])
    @debit_card = DebitCard.new
    @debit_cards = DebitCard.where(user_id: @user.id)
  end

  # POST /users/:permalink/debit_cards
  def create
    create_params = create_params_permit!
    @card = @user.debit_cards.create!(create_params)
    flash[:success] = "Debit card created successfully!"
    redirect_to debit_cards_path(@user.permalink)
  end

  private

    def find_user
      find_params = find_user_params_permit!
      @user = User.find_by_permalink(find_params[:permalink])
      raise Errors::UserNotFound.new("User not found") if @user.nil?
    end

    def find_user_params_permit!
      params.permit(
        :permalink
      ).to_h
    end

    def update_params_permit!
      params.require(:debit_card).permit(
        :card_number,
        :expiration_month,
        :expiration_year,
        :cvv
      ).to_h
    end

    def create_params_permit!
      params.require(:debit_card).permit(
        :card_number,
        :expiration_month,
        :expiration_year,
        :cvv
      ).to_h
    end

    def new_params_permit!
      params.permit(
        :permalink
      ).to_h
    end

    def find_debit_card
      @debit_card = DebitCard.find_by_id!(find_debit_card_params[:id])
    end

    def find_debit_card_params
      params.permit(:id).to_h
    end

    def handle_errors
      yield
    rescue Errors::UserNotFound => e
      flash[:error] = e.message
      redirect_to users_path
    rescue ActiveRecord::RecordNotFound => e
      flash[:error] = e.message
      redirect_to debit_cards_path
    rescue ActiveRecord::RecordInvalid => e
      record = e.record
      errors_message = record.errors.full_messages.join(", ")
      path_to_redirect_to = record.persisted? ? record.reload : new_debit_card_path
      flash[:error] = errors_message
      redirect_to path_to_redirect_to
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  around_action :handle_errors
  before_action :find_user, only: [:show, :edit, :update]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/:permalink
  def show
  end

  # GET /users/:permalink/edit
  def edit
  end

  # PUT /users/:permalink
  def update
    update_params = update_params_permit!
    @user.update!(update_params)
    flash[:success] = "User updated successfully!"
    redirect_to user_path(@user.permalink)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    create_params = create_params_permit!
    @user = User.create!(create_params)
    flash[:success] = "User created successfully!"
    redirect_to @user
  end

  private

    def update_params_permit!
      params.require(:user).permit(
        :first_name,
        :last_name
      ).to_h
    end

    def create_params_permit!
      params.require(:user).permit(
        :first_name,
        :last_name
      ).to_h
    end

    def find_user
      @user = User.find_by_permalink!(find_user_params[:permalink])
    end

    def find_user_params
      params.permit(:permalink).to_h
    end

    def handle_errors
      yield
    rescue ActiveRecord::RecordNotFound => e
      flash[:error] = e.message
      redirect_to users_path
    rescue ActiveRecord::RecordInvalid => e
      record = e.record
      errors_message = record.errors.full_messages.join(", ")
      path_to_redirect_to = record.persisted? ? record.reload : new_user_path
      flash[:error] = errors_message
      redirect_to path_to_redirect_to
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  DEFAULT_ALERT = 'alert-dark'.freeze

  FLASHES = {
      'success' => 'alert-success',
      'info' => 'alert-info',
      'warning' => 'alert-warning',
      'error' => 'alert-danger'
    }.freeze

  def get_flash_class(type = nil)
    FLASHES[type].present? ? FLASHES[type] : DEFAULT_ALERT
  end

  def format_card_number(last_four)
    prefix = "*" * 12
    prefix + last_four
  end

  def format_expiration_month(month)
    month < 10 ? "0#{month}" : month
  end

  def format_card_expiration_date(month, year)
    month = format_expiration_month(month)
    "#{month}/#{year}"
  end
end

app/helpers/debit_card_helper.rb
module DebitCardHelper
end

app/helpers/errors.rb
module Errors
  class UserNotFound < StandardError; end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/debit_cards/edit.html.haml
.row
  .col-xs-3
    %h1 User details
    %table.table.table-bordered
      %tr
        %th.col-md-5 First Name:
        %td.text-left=@user.first_name
      %tr
        %th Last Name:
        %td=@user.last_name
  .col-md-8
    .row
      .col-xs-6
        %h1 Debit cards
        =form_for(@debit_card, url: debit_card_path(@user.permalink, @debit_card.id), method: :put) do |f|
          .panel.panel-default
            .panel-heading
              Update debit card
            .panel-body
              %p.text-warning
                Warning: You are about to update this debit card.
              %table.table
                %tr
                  %th Card number
                  %td
                    = f.text_field :card_number, maxlength: 16, size: 20, placeholder: "1234567890123456"
                %tr
                  %th Expiration month
                  %td
                    = f.text_field :expiration_month, maxlength: 2, size: 20, placeholder: "02"
                %tr
                  %th Expiration year
                  %td
                    = f.text_field :expiration_year, maxlength: 4, size: 20, placeholder: "2020"
                %tr
                  %th CVV
                  %td
                    = f.text_field :cvv, maxlength: 3, size: 20, placeholder: "123"
              %tr
                %th
                %td
                  = f.submit 'Save card', :class => 'btn btn-primary btn-sm'
                  =link_to 'Cancel', debit_card_path(@user.permalink, @debit_card.id), :class => 'btn btn-primary btn-sm'

app/views/debit_cards/index.html.haml
.row
  .col-xs-3
    = render "users/user_details"
  .col-xs-4
    %h1 Debit cards
    - if @user.debit_cards.present?
      %table.table.table-striped
        %tr
          %th Card number
          %th Expiration
        - @user.debit_cards.each do |card|
          %tr
            %td
              =link_to format_card_number(card.last_four), debit_card_path(@user.permalink, card)
            %td
              =format_card_expiration_date(card.expiration_month, card.expiration_year)
    - else
      %p.text-info
        The user does not have any debit cards on file
    =link_to "Add new card", new_debit_card_path(@user.permalink), :class => 'btn btn-primary btn-sm'

app/views/debit_cards/new.html.haml
.row
  .col-xs-3
    %h1 User details
    %table.table.table-bordered
      %tr
        %th.col-md-5 First Name:
        %td.text-left=@user.first_name
      %tr
        %th Last Name:
        %td=@user.last_name
  .col-md-8
    .row
      .col-xs-6
        %h1 Debit cards
        =form_for(@debit_card) do |f|
          .panel.panel-default
            .panel-heading
              New debit card
            .panel-body
              %table.table
                %tr
                  %th Card number
                  %td
                    = f.text_field :card_number, maxlength: 16, size: 20, placeholder: "1234567890123456"
                %tr
                  %th Expiration month
                  %td
                    = f.text_field :expiration_month, maxlength: 2, size: 20, placeholder: "02"
                %tr
                  %th Expiration year
                  %td
                    = f.text_field :expiration_year, maxlength: 4, size: 20, placeholder: "2020"
                %tr
                  %th CVV
                  %td
                    = f.text_field :cvv, maxlength: 3, size: 20, placeholder: "123"
              %tr
                %th
                %td
                  = f.submit 'Save card', :class => 'btn btn-primary btn-sm'

app/views/debit_cards/show.html.haml
.row
  .col-xs-3
    = render "users/user_details"
  .col-md-8
    .row
      .col-xs-7
        %h1 Debit cards
        .panel.panel-default
          .panel-heading
            Debit card on file
          .panel-body
            %table.table
              %tr
                %th Card number
                %td
                  =format_card_number(@debit_card.last_four)
              %tr
                %th Expiration
                %td
                  =format_card_expiration_date(@debit_card.expiration_month, @debit_card.expiration_year)
            =link_to "Update debit card", edit_debit_card_path(@user.permalink, @debit_card.id), :class => 'btn btn-primary btn-sm'
            =link_to "Submit payment!", make_payment_debit_card_path(@user.permalink, @debit_card.id), :method => "post", :class => 'btn btn-warning btn-sm'

        =link_to "View user's debit cards", debit_cards_path(@user.permalink), :class => 'btn btn-default btn-sm'

app/views/layouts/_notifications.html.haml
- if flash.present?
  .growl.growl-static
    - flash.each do |type, message|
      .alert.alert-dismissable{:role => "alert", :class => get_flash_class(type), :style => "width: 585px"}
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %strong
          = "#{type.to_s.titleize}: "
        = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DebitCardPage
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top.app-navbar
      .container
        #navbar-collapse-main.navbar-collapse.collapse
          %ul.nav.navbar-nav.hidden-xs
            %li
              =link_to 'Home', root_path
            %li
              =link_to 'Users', users_path

    %br
    %br
    %br
    #main-container.container
      = render 'layouts/notifications'
      = yield

app/views/users/_user_details.html.haml
%h1 User details
%table.table.table-bordered
  %tr
    %th.col-md-5 First Name:
    %td.text-left=@user.first_name
  %tr
    %th Last Name:
    %td=@user.last_name

=link_to "Edit user", edit_user_path(@user.permalink), :class => 'btn btn-primary btn-sm'

app/views/users/edit.html.haml
.row
  .col-xs-4
    =form_for(@user, url: user_path(@user.permalink), method: :put) do |f|
      .panel.panel-default
        .panel-heading
          Edit user details
        .panel-body
          %table.table
            %tr
              %th First name
              %td
                = f.text_field :first_name
            %tr
              %th Last name
              %td
                = f.text_field :last_name
          %tr
            %th
            %td
              = f.submit 'Save', :class => 'btn btn-primary btn-sm'

app/views/users/index.html.haml
.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        Registered users
      .panel-body
        %table.table.table-hover
          %tr
            %th First name
            %th Last name
          - @users.each do |user|
            %tr
              %td
                =link_to user.first_name, user_path(user.permalink), :class => 'blue'
              %td
                =user.last_name

    =link_to "Register new user", new_user_path, :class => 'btn btn-primary btn-sm'

app/views/users/new.html.haml
.row
  .col-xs-4
    =form_for(@user) do |f|
      .panel.panel-default
        .panel-heading
          New user registration
        .panel-body
          %table.table
            %tr
              %th First name
              %td
                = f.text_field :first_name
            %tr
              %th Last name
              %td
                = f.text_field :last_name
          %tr
            %th
            %td
              = f.submit 'Register', :class => 'btn btn-primary btn-sm'

app/views/users/show.html.haml
.row
  .col-xs-3
    = render "user_details"
  .col-xs-4
    %h1 Debit cards
    - if @user.debit_cards.present?
      %table.table.table-striped
        %tr
          %th Card number
          %th Expiration
        - @user.debit_cards.each do |card|
          %tr
            %td
              =link_to format_card_number(card.last_four), debit_card_path(@user.permalink, card)
            %td
              =format_card_expiration_date(card.expiration_month, card.expiration_year)
    - else
      %p.text-info
        The user does not have any debit cards on file
    =link_to "Add new card", new_debit_card_path(@user.permalink), :class => 'btn btn-primary btn-sm'